name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env: 
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "Logging environment variables"
      - run: echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}"
      - run: echo "REACT_APP_API_KEY=${{ env.REACT_APP_API_KEY }}" > .env
      - run: cat .env  # Optional: To verify that .env file is created successfully
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIIMGTOOLSPROD }}'
          channelId: live
          projectId: aiimgtoolsprod
